
    export const errorCodes = {
        Daikin: [
          { code: "U1", description: "Ters Faz" },
          { code: "U2", description: "Düşük Basınç" },
          { code: "U3", description: "Yüksek Basınç" },
          { code: "U4", description: "Ic ve col arasindaki elaqe kesilib" },
          { code: "U5", description: "Dış Ünite Arızası" },
          { code: "U6", description: "İç Ünite Arızası" },
          { code: "U7", description: "Güç Arızası" },
          { code: "U8", description: "Baskı Sensörü Arızası" },
          { code: "U9", description: "Ters Faz" },
          { code: "E1", description: "Düşük Voltaj" },
          { code: "E2", description: "Aşırı Yük" },
        ],
        Mitsubishi: [
          { code: "E01", description: "Pult ile elaqe kesilib" },
          { code: "E02", description: "Düşük Basınç" },
          { code: "E03", description: "Yüksek Basınç" },
          { code: "E04", description: "Hava Akışı Arızası" },
          { code: "E05", description: "Dış Ünite Arızası" },
          { code: "E06", description: "İç Ünite Arızası" },
          { code: "E07", description: "Güç Arızası" },
          { code: "E08", description: "Baskı Sensörü Arızası" },
          { code: "E09", description: "Pompa Sorunu" },
          { code: "E10", description: "Düşük Gaz" },
          { code: "U1", description: "Ters Faz" },
        ],
        Gree: [
          { code: "E01", description: "Sensör Arızası" },
          { code: "E02", description: "Düşük Basınç" },
          { code: "E03", description: "Yüksek Basınç" },
          { code: "E04", description: "Hava Akışı Arızası" },
          { code: "E05", description: "Dış Ünite Arızası" },
          { code: "E06", description: "İç Ünite Arızası" },
          { code: "E07", description: "Güç Arızası" },
          { code: "E08", description: "Baskı Sensörü Arızası" },
          { code: "E09", description: "Kompresör Arızası" },
          { code: "E10", description: "Termostat Arızası" },
          { code: "U1", description: "Ters Faz" },
        ],
        Toshiba: [
          { code: "E01", description: "Sensör Arızası" },
          { code: "E02", description: "Düşük Basınç" },
          { code: "E03", description: "Yüksek Basınç" },
          { code: "E04", description: "Hava Akışı Arızası" },
          { code: "E05", description: "Dış Ünite Arızası" },
          { code: "E06", description: "İç Ünite Arızası" },
          { code: "E07", description: "Güç Arızası" },
          { code: "E08", description: "Baskı Sensörü Arızası" },
          { code: "E09", description: "Pompa Sorunu" },
          { code: "E10", description: "Termostat Arızası" },
          { code: "U1", description: "Ters Faz" },
        ],
        Panasonic: [
          { code: "E01", description: "Sensör Arızası" },
          { code: "E02", description: "Düşük Basınç" },
          { code: "E03", description: "Yüksek Basınç" },
          { code: "E04", description: "Hava Akışı Arızası" },
          { code: "E05", description: "Dış Ünite Arızası" },
          { code: "E06", description: "İç Ünite Arızası" },
          { code: "E07", description: "Güç Arızası" },
          { code: "E08", description: "Baskı Sensörü Arızası" },
          { code: "E09", description: "Kompresör Arızası" },
          { code: "E10", description: "Düşük Gaz" },
          { code: "U1", description: "Ters Faz" },
        ],
        Sanyo: [
          { code: "E01", description: "Daccik xarabdi" },
          { code: "E02", description: "Düşük Basınç" },
          { code: "E03", description: "Yüksek Basınç" },
          { code: "E04", description: "Hava Akışı Arızası" },
          { code: "E05", description: "Dış Ünite Arızası" },
          { code: "E06", description: "İç Ünite Arızası" },
          { code: "E07", description: "Güç Arızası" },
          { code: "E08", description: "Baskı Sensörü Arızası" },
          { code: "E09", description: "Kompresör Arızası" },
          { code: "E10", description: "Düşük Gaz" },
          { code: "U1", description: "Ters Faz" },
        ],
      };
